/**
 * 🤖 AI-Generated Project: Minimalist Homepage
 * Generated by: Claude Sonnet 4 (Anthropic)
 * Date: 2024
 * Description: Main App Initialization - Coordinates all widgets
 * Tech Stack: Vanilla HTML/CSS/JS + Tailwind CSS
 * License: MIT
 */

// ============================================================================
// MAIN APP INITIALIZATION
// ============================================================================

/**
 * Initialize the main application and coordinate all widgets
 */
function initializeApp() {
    // Initialize todo functionality
    const todoForm = document.getElementById('todoForm');
    const todoFilter = document.getElementById('todoFilter');
    const todoDateToggle = document.getElementById('todoDateToggle');
    const todoDueDate = document.getElementById('todoDueDate');
    const todoInput = document.getElementById('todoInput');
    
    console.log('Initializing todo elements:', {
        todoForm: !!todoForm,
        todoFilter: !!todoFilter,
        todoDateToggle: !!todoDateToggle,
        todoDueDate: !!todoDueDate,
        todoInput: !!todoInput
    });
    
    if (todoForm) todoForm.addEventListener('submit', handleTodoSubmit);
    if (todoFilter) todoFilter.addEventListener('change', handleTodoFilterChange);
    if (todoDateToggle) {
        console.log('Adding click listener to date toggle button');
        todoDateToggle.addEventListener('click', handleDateToggle);
    }
    if (todoDueDate) todoDueDate.addEventListener('change', handleDateChange);
    if (todoInput) todoInput.addEventListener('keydown', handleTodoKeyboard);
    
    loadTodoFilterPreference();
    
    // Render initial todos
    renderTodos();
    
    // Initialize other components
    // (Clock, search, calendar, etc. are initialized immediately when script loads)
}

// Initialize app immediately (widget loader ensures DOM is ready)
initializeApp(); 