/**
 * 🤖 AI-Generated Project: Minimalist Homepage
 * Generated by: Claude Sonnet 4 (Anthropic)
 * Date: 2024
 * Description: Music Widget - YouTube Music player integration
 * Tech Stack: Vanilla HTML/CSS/JS + Tailwind CSS
 * License: MIT
 */

// ============================================================================
// YOUTUBE MUSIC PLAYER (Ticket 4)
// ============================================================================

/**
 * Handles YouTube Music playlist button click
 * Note: Replace PLAYLIST_ID with actual playlist ID
 */
function handleMusicPlay() {
    const playlistId = 'RDCLAK5uy_nFD4lodGvr1kb0xlJOOfEi0tGWI7cQKK0'; // TODO: Replace with actual playlist ID
    const musicUrl = `https://music.youtube.com/playlist?list=${playlistId}&play=1`;
    window.open(musicUrl, '_blank');
}

// Initialize YouTube Music functionality
document.getElementById('playMusicBtn').addEventListener('click', handleMusicPlay); 