/**
 * 🤖 AI-Generated Project: Minimalist Homepage
 * Generated by: Claude Sonnet 4 (Anthropic)
 * Date: 2024
 * Description: Salutation Widget - Displays time-aware greetings
 * Tech Stack: Vanilla HTML/CSS/JS + Tailwind CSS
 * License: MIT
 */

// ============================================================================
// SALUTATION MESSAGES (Ticket 12)
// ============================================================================

// Salutation messages array
const salutations = [
    'Good Morning',
    'Rise and Shine',
    'Hello there',
    'Welcome back',
    'Greetings',
    'Hey there',
    'Good to see you',
    'Hello friend',
    'Welcome',
    'Hi there'
];

/**
 * Gets a time-aware greeting based on current hour
 * @returns {string} Time-appropriate greeting
 */
function getTimeAwareGreeting() {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good Morning';
    if (hour < 17) return 'Good Afternoon';
    return 'Good Evening';
}

/**
 * Sets a random salutation message
 */
function setRandomSalutation() {
    const salutationElement = document.getElementById('salutation');
    if (!salutationElement) return;
    
    // 70% chance for time-aware greeting, 30% for random salutation
    const useTimeAware = Math.random() < 0.7;
    
    let message;
    if (useTimeAware) {
        message = getTimeAwareGreeting();
    } else {
        message = salutations[Math.floor(Math.random() * salutations.length)];
    }
    
    salutationElement.textContent = message;
}

// Initialize salutation on page load
setRandomSalutation(); 