/**
 * 🤖 AI-Generated Project: Minimalist Homepage
 * Generated by: Claude Sonnet 4 (Anthropic)
 * Date: 2024
 * Description: Utility Functions - Common utilities and debug functions
 * Tech Stack: Vanilla HTML/CSS/JS + Tailwind CSS
 * License: MIT
 */

// ============================================================================
// DATA MANAGEMENT (Ticket 2)
// ============================================================================

/**
 * Clears all data from localStorage
 */
function clearAllData() {
    const confirmed = confirm(
        'Are you sure you want to clear all data?\n\n' +
        'This will remove:\n' +
        '• All to-do tasks\n' +
        '• All sticky notes\n' +
        '• All calendar events\n' +
        '• Search engine preferences\n\n' +
        'This action cannot be undone.'
    );
    
    if (confirmed) {
        localStorage.clear();
        location.reload();
    }
}

// Initialize data management functionality
document.getElementById('clearAllDataBtn')?.addEventListener('click', clearAllData);

// Initialize easter egg functionality
document.getElementById('easterEggClose')?.addEventListener('click', (event) => {
    event.preventDefault();
    event.stopPropagation();
    hideEasterEggResult();
});

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Shows a simple alert message (can be enhanced with a proper toast notification)
 * @param {string} message - Message to display
 */
function showMessage(message) {
    alert(message); // TODO: Replace with proper toast notification
}

// ============================================================================
// DEBUG FUNCTIONS
// ============================================================================

/**
 * Test function to check dropdown functionality (for debugging)
 */
function testDropdownFunctionality() {
    const dropdown = document.getElementById('searchEngineDropdown');
    const toggle = document.getElementById('searchEngineToggle');
    const easterEggOutput = document.getElementById('easterEggOutput');
    
    console.log('🧪 TEST: Checking dropdown functionality...');
    console.log('🧪 Dropdown element:', !!dropdown);
    console.log('🧪 Toggle element:', !!toggle);
    console.log('🧪 Easter egg output:', !!easterEggOutput);
    
    if (dropdown) {
        console.log('🧪 Dropdown classes:', dropdown.className);
        console.log('🧪 Dropdown hidden:', dropdown.classList.contains('hidden'));
    }
    
    if (easterEggOutput) {
        console.log('🧪 Easter egg classes:', easterEggOutput.className);
        console.log('🧪 Easter egg hidden:', easterEggOutput.classList.contains('hidden'));
    }
    
    console.log('🧪 isDropdownOpen state:', isDropdownOpen);
}

/**
 * Force reset all UI elements to correct state (for debugging)
 */
function forceResetUI() {
    // Force close dropdown
    const dropdown = document.getElementById('searchEngineDropdown');
    if (dropdown) {
        dropdown.classList.add('hidden');
        isDropdownOpen = false;
    }
    
    // Force hide easter egg output
    const easterEggOutput = document.getElementById('easterEggOutput');
    if (easterEggOutput) {
        easterEggOutput.classList.add('hidden');
    }
    
    // Clear search input
    const searchInput = document.getElementById('searchInput');
    if (searchInput) {
        searchInput.value = '';
        searchInput.focus();
    }
}

// Make test functions globally available
window.testDropdownFunctionality = testDropdownFunctionality;
window.forceResetUI = forceResetUI; 